services:
  - type: web
    name: strapi
    env: node
    plan: free
    buildCommand: npm install && npm run build # Use 'npm run build' instead of 'npm build'
    startCommand: rsync -a public/ /data/public/ && npm start
    healthCheckPath: /_health
    autoDeploy: false
    envVars:
      NODE_VERSION: ~16.14.0 # Use a different syntax for specifying environment variables
      NODE_ENV: production
      DATABASE_FILENAME: /data/strapi.db
      JWT_SECRET:
        generateValue: true
      ADMIN_JWT_SECRET:
        generateValue: true
      APP_KEYS:
        generateValue: true
